### Get a new JWT token
GET http://localhost:3000/auth/token

### Access Protected Route (requires token)
# Replace 'YOUR_TOKEN_HERE' with the token returned from the request above
GET http://localhost:3000/protected
Authorization: Bearer YOUR_TOKEN_HERE


### Get all users
GET http://localhost:3000/users

###  Create a new user
POST http://localhost:3000/users
Content-Type: application/json

{
  "_id": 1,
  "name": "Utkarsh",
  "age": 21,
  "course": "B.Tech",
  "skills": ["Node.js", "MongoDB"],
  "address": { "city": "Mathura", "pincode": 281001 },
  "isActive": true,
  "status": "active",
  "verified": true
}
